### ISSUE TITLE
Check fails to traverse entire filesystem when -o is unset or too low.

### ISSUE THREAD

**Issue by satkunas** [BerniWittmann/vue-unused-components-checker#3]
When omitting `-o` from command line, or using a low `-o` to limit open files, the check fails to traverse the entire filesystem of a large project. Gradually increasing the openfile limit with `-o` leads to out of memory errors before all unused components are found.

Since it's not possible to increase the number of open files as stated in https://github.com/BerniWittmann/vue-unused-components-checker/issues/2 the tool is only usable for small projects.

**Comment by BerniWittmann** [comment]
Could you describe how failing to traverse the entire filetree manifests? 
Have you tried to exclude unnecessary files like assets/dependencies to reduce the load on the checker?

**Comment by satkunas** [comment]
> Have you tried to exclude unnecessary files like assets/dependencies to reduce the load on the checker?

Yes, but it's kind of pointless to have to exclude all the extraneous files in order to limit the workload on the tool. The tool should do this itself. If the tool fails in the assets/deps because of a design flaw, then it's likely to fail in a large project as well, which appears to be my case.

> Could you describe how failing to traverse the entire filetree manifests?

Producing an example that includes hundreds of files is beyond the amount of work needed to manually search for unused components in the first place.

**Comment by BerniWittmann** [comment]
You‘re right @satkunas, optimally the tool would do it itself, so users do not have to worry about stuff like that.

However, I developed this small script for a project of mine and made it public, yet I do not have the time right now to refactor and come up with a more performance architecture.  That‘s the reason why I told you to exclude stuff, since using a Regex to include some folders is a compromise between usability and the efforts I would have to invest in a better architecture. 

If you know of a better architecture, please feel free to contribute with a PR or comment an idea so that I may be able to incorporate that in the future. I am open for contributions may that be PRs or ideas.


Regarding your second point: I may have been unclear. I was not asking for a reproduction (which I know would be huge), but more how do you know that it did not traverse everything? Did you know of a specific case which was not reported, or did it throw some error?

**Comment by satkunas** [comment]
> how do you know that it did not traverse everything? Did you know of a specific case which was not reported, or did it throw some error?

I'm in the middle of a large refactor I tried using the tool to see if I missed anything. When using the tool it failed to pickup approximately 20-30 files that are known to be no longer in use. In fact the tool completed without error and with an empty list.

**Comment by BerniWittmann** [comment]
Got it. Maybe you could provide how you import a component e.g `import ... from ...` so i can check 

If you still have Tests where these files are imported that could also cause these false negatives, ignoring those files would maybe help there

**Comment by satkunas** [comment]
Here's an example of our import usage:

https://github.com/inverse-inc/packetfence/blob/devel/html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js

**Comment by BerniWittmann** [comment]
Thank you very much. I already see one issue. The regex to check the import https://github.com/BerniWittmann/vue-unused-components-checker/blob/a4f2abd17c913298054e9316b4751ece2c3395dc/checker.js#L19 does not detect importing of files with the following pattern 
`import(/* webpackChunkName: "Configuration" */ '../_components/PoliciesAccessControlSection')` 
However, this should not be the root of your problem, since this would generate false positives and not false negatives... 

Could you maybe tell me one component that is not correctly detected as unused, so I can test and debug this issue a little?

**Comment by BerniWittmann** [comment]
The newest version `1.1.2` now includes support for `import(` calls, so this may be solved with the new version
